FactoryBot.define do
  factory :attraction do
    sequence(:name) { |n| "黄鹤楼公园#{n}" }
    province { "湖北" }
    city { "武汉" }
    district { "武昌区" }
    address { "武汉市武昌区蛇山" }
    latitude { 30.5450 }
    longitude { 114.2968 }
    rating { 4.5 }
    review_count { 0 }
    opening_hours { "09:00-17:00" }
    phone { "027-12345678" }
    description { "著名景点" }
    # slug will be auto-generated by FriendlyId from name
    
    after(:create) do |attraction|
      # Reload to ensure slug is populated from FriendlyId
      attraction.reload
    end
  end
end
