FactoryBot.define do
  factory :charter_route do
    name { '黄鹤楼-东湖-楚河汉街一日游' }
    association :city
    slug { nil }  # Will be auto-generated by FriendlyId
    duration_days { 1 }
    distance_km { 50 }
    category { 'classic' }  # Valid: featured, classic, hot
    description { '经典武汉一日游路线，游览黄鹤楼、东湖、楚河汉街等著名景点' }
    price_from { 600.0 }
    highlights { '黄鹤楼登高、东湖游船、楚河汉街美食' }
    cover_image_url { 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800' }
  end
end
