# 清空现有数据
Car.destroy_all

puts "Creating cars..."

cars_data = [
  # ============ 武汉 ============
  {
    brand: "特斯拉",
    car_model: "Model 3",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 72,
    total_price: 324,
    discount_amount: 72,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "舒适轿车 | 5座4门 | 自动挡 | 纯电动",
    tags: "销量第一,机车特惠,VR看车",
    image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89",
    is_featured: true,
    is_available: true,
    sales_rank: 1
  },
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 150,
    total_price: 600,
    discount_amount: 50,
    location: "武汉",
    pickup_location: "武汉站东广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "高铁便捷,商务首选",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: true,
    is_available: true,
    sales_rank: 2
  },
  {
    brand: "大众",
    car_model: "帕萨特",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.8T",
    price_per_day: 165,
    total_price: 660,
    discount_amount: 60,
    location: "武汉",
    pickup_location: "汉口站北广场租车点",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.8T",
    tags: "商务优选,车站直达",
    image_url: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982",
    is_featured: false,
    is_available: true,
    sales_rank: 3
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 170,
    total_price: 680,
    discount_amount: 70,
    location: "武汉",
    pickup_location: "武昌站南广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "品质保证,可靠舒适",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: false,
    is_available: true,
    sales_rank: 4
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 280,
    total_price: 1120,
    discount_amount: 80,
    location: "武汉",
    pickup_location: "光谷广场租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,舒适空间",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 5
  },
  {
    brand: "丰田",
    car_model: "汉兰达",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 320,
    total_price: 1280,
    discount_amount: 90,
    location: "武汉",
    pickup_location: "江汉路步行街租车点",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "大空间,家庭出游",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: false,
    is_available: true,
    sales_rank: 6
  },
  {
    brand: "奥迪",
    car_model: "A6L",
    category: "豪华轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 380,
    total_price: 1520,
    discount_amount: 100,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "豪华轿车 | 5座4门 | 自动挡 | 2.0T",
    tags: "豪华商务,尊贵体验",
    image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8",
    is_featured: false,
    is_available: true,
    sales_rank: 7
  },

  # ============ 深圳 ============
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 120,
    total_price: 360,
    discount_amount: 40,
    location: "深圳",
    pickup_location: "宝安机场T3航站楼租车中心",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "城市热销,经济实惠",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 13
  },
  {
    brand: "别克",
    car_model: "凯越",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.3L",
    price_per_day: 95,
    total_price: 285,
    discount_amount: 50,
    location: "深圳",
    pickup_location: "宝安机场GTC地面交通中心",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.3L",
    tags: "总价最低,机车特惠",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: true,
    is_available: true,
    sales_rank: 14
  },
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 110,
    total_price: 330,
    discount_amount: 30,
    location: "深圳",
    pickup_location: "宝安机场停车场租车点",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "低价好车,城市热销",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 15
  },
  {
    brand: "丰田",
    car_model: "卡罗拉",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 105,
    total_price: 315,
    discount_amount: 35,
    location: "深圳",
    pickup_location: "深圳北站西广场租车中心",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "车站便捷,热门车型",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 101
  },
  {
    brand: "日产",
    car_model: "轩逸",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.6L",
    price_per_day: 130,
    total_price: 390,
    discount_amount: 45,
    location: "深圳",
    pickup_location: "深圳北站东广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.6L",
    tags: "舒适经济,车站专属",
    image_url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6",
    is_featured: false,
    is_available: true,
    sales_rank: 102
  },
  {
    brand: "比亚迪",
    car_model: "秦PLUS DM-i",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "插电混动",
    engine: "混合动力",
    price_per_day: 115,
    total_price: 345,
    discount_amount: 50,
    location: "深圳",
    pickup_location: "深圳站罗湖口岸租车点",
    features: "新能源 | 5座4门 | 自动挡 | 插电混动",
    tags: "新能源,节能环保",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: false,
    is_available: true,
    sales_rank: 103
  },
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 180,
    total_price: 540,
    discount_amount: 60,
    location: "深圳",
    pickup_location: "福田中心区会展中心租车点",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "商务首选,CBD专属",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: true,
    is_available: true,
    sales_rank: 105
  },
  {
    brand: "特斯拉",
    car_model: "Model 3",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 280,
    total_price: 840,
    discount_amount: 100,
    location: "深圳",
    pickup_location: "福田区皇岗口岸租车中心",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "智能电动,科技体验",
    image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89",
    is_featured: true,
    is_available: true,
    sales_rank: 107
  },

  # ============ 北京 ============
  {
    brand: "大众",
    car_model: "速腾",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.4T",
    price_per_day: 135,
    total_price: 405,
    discount_amount: 45,
    location: "北京",
    pickup_location: "首都国际机场T3航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.4T",
    tags: "机场特惠,热门车型",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 201
  },
  {
    brand: "别克",
    car_model: "英朗",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.3T",
    price_per_day: 125,
    total_price: 375,
    discount_amount: 40,
    location: "北京",
    pickup_location: "首都国际机场T2航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.3T",
    tags: "经济实惠,品质之选",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: true,
    is_available: true,
    sales_rank: 202
  },
  {
    brand: "本田",
    car_model: "思域",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 155,
    total_price: 465,
    discount_amount: 50,
    location: "北京",
    pickup_location: "大兴国际机场综合服务楼",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "运动时尚,年轻选择",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 203
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 185,
    total_price: 555,
    discount_amount: 60,
    location: "北京",
    pickup_location: "北京南站北广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "高铁直达,舒适商务",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 204
  },
  {
    brand: "奥迪",
    car_model: "A4L",
    category: "豪华轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 350,
    total_price: 1050,
    discount_amount: 100,
    location: "北京",
    pickup_location: "北京西站南广场停车楼",
    features: "豪华轿车 | 5座4门 | 自动挡 | 2.0T",
    tags: "商务豪华,尊贵出行",
    image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8",
    is_featured: false,
    is_available: true,
    sales_rank: 205
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 320,
    total_price: 960,
    discount_amount: 80,
    location: "北京",
    pickup_location: "朝阳区国贸CBD租车点",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,多人出行",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 206
  },
  {
    brand: "特斯拉",
    car_model: "Model Y",
    category: "新能源",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 380,
    total_price: 1140,
    discount_amount: 120,
    location: "北京",
    pickup_location: "三里屯太古里租车服务站",
    features: "新能源 | 5座5门 | 自动挡 | 纯电动",
    tags: "智能SUV,科技体验",
    image_url: "https://images.unsplash.com/photo-1617788138017-80ad40651399",
    is_featured: true,
    is_available: true,
    sales_rank: 207
  },

  # ============ 上海 ============
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 128,
    total_price: 384,
    discount_amount: 42,
    location: "上海",
    pickup_location: "浦东国际机场T1航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "机场热销,经济之选",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 301
  },
  {
    brand: "丰田",
    car_model: "雷凌",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.2T",
    price_per_day: 118,
    total_price: 354,
    discount_amount: 38,
    location: "上海",
    pickup_location: "浦东国际机场T2航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.2T",
    tags: "省油耐用,品质可靠",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 302
  },
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 188,
    total_price: 564,
    discount_amount: 62,
    location: "上海",
    pickup_location: "虹桥国际机场T2航站楼",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "商务首选,舒适驾乘",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: true,
    is_available: true,
    sales_rank: 303
  },
  {
    brand: "日产",
    car_model: "天籁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 178,
    total_price: 534,
    discount_amount: 58,
    location: "上海",
    pickup_location: "上海虹桥站西广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "高铁便捷,移动沙发",
    image_url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6",
    is_featured: true,
    is_available: true,
    sales_rank: 304
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 328,
    total_price: 984,
    discount_amount: 85,
    location: "上海",
    pickup_location: "上海南站南广场停车场",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务专车,宽敞舒适",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 305
  },
  {
    brand: "奔驰",
    car_model: "E级",
    category: "豪华轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 480,
    total_price: 1440,
    discount_amount: 120,
    location: "上海",
    pickup_location: "陆家嘴金融区租车服务站",
    features: "豪华轿车 | 5座4门 | 自动挡 | 2.0T",
    tags: "奢华体验,商务至尊",
    image_url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738",
    is_featured: false,
    is_available: true,
    sales_rank: 306
  },
  {
    brand: "蔚来",
    car_model: "ET5",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 298,
    total_price: 894,
    discount_amount: 100,
    location: "上海",
    pickup_location: "徐家汇商圈租车点",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "智能座舱,换电便捷",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: true,
    is_available: true,
    sales_rank: 307
  },

  # ============ 广州 ============
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 115,
    total_price: 345,
    discount_amount: 35,
    location: "广州",
    pickup_location: "白云国际机场T1航站楼",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "超跑GK5,空间魔术",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 401
  },
  {
    brand: "丰田",
    car_model: "卡罗拉",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 108,
    total_price: 324,
    discount_amount: 32,
    location: "广州",
    pickup_location: "白云国际机场T2航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "省油王,家用首选",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 402
  },
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 175,
    total_price: 525,
    discount_amount: 55,
    location: "广州",
    pickup_location: "广州南站东广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "高铁站直达,商务舒适",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: true,
    is_available: true,
    sales_rank: 403
  },
  {
    brand: "日产",
    car_model: "轩逸",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.6L",
    price_per_day: 132,
    total_price: 396,
    discount_amount: 42,
    location: "广州",
    pickup_location: "广州东站南广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.6L",
    tags: "移动沙发,舒适代步",
    image_url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6",
    is_featured: true,
    is_available: true,
    sales_rank: 404
  },
  {
    brand: "丰田",
    car_model: "汉兰达",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 315,
    total_price: 945,
    discount_amount: 85,
    location: "广州",
    pickup_location: "天河体育中心租车点",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "七座SUV,家庭出游",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 405
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 295,
    total_price: 885,
    discount_amount: 75,
    location: "广州",
    pickup_location: "珠江新城CBD租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务专车,陆地公务舱",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 406
  },
  {
    brand: "比亚迪",
    car_model: "汉EV",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 268,
    total_price: 804,
    discount_amount: 90,
    location: "广州",
    pickup_location: "琶洲会展中心租车点",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "旗舰电动,科技豪华",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: false,
    is_available: true,
    sales_rank: 407
  },

  # ============ 成都 ============
  {
    brand: "大众",
    car_model: "速腾",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.4T",
    price_per_day: 122,
    total_price: 366,
    discount_amount: 38,
    location: "成都",
    pickup_location: "双流国际机场T2航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.4T",
    tags: "机场热销,德系品质",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 501
  },
  {
    brand: "别克",
    car_model: "英朗",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.3T",
    price_per_day: 112,
    total_price: 336,
    discount_amount: 35,
    location: "成都",
    pickup_location: "双流国际机场T1航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.3T",
    tags: "经济实用,口碑之选",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: true,
    is_available: true,
    sales_rank: 502
  },
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 168,
    total_price: 504,
    discount_amount: 52,
    location: "成都",
    pickup_location: "成都东站东广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "高铁专属,商务之选",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: true,
    is_available: true,
    sales_rank: 503
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 172,
    total_price: 516,
    discount_amount: 55,
    location: "成都",
    pickup_location: "成都南站南广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "高铁站点,品质保证",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 504
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 285,
    total_price: 855,
    discount_amount: 75,
    location: "成都",
    pickup_location: "春熙路太古里租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,多人出行",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 505
  },
  {
    brand: "丰田",
    car_model: "汉兰达",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 298,
    total_price: 894,
    discount_amount: 80,
    location: "成都",
    pickup_location: "天府广场租车点",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "大空间SUV,家庭首选",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: false,
    is_available: true,
    sales_rank: 506
  },
  {
    brand: "理想",
    car_model: "L8",
    category: "新能源",
    seats: 6,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "增程式",
    engine: "增程式",
    price_per_day: 488,
    total_price: 1464,
    discount_amount: 150,
    location: "成都",
    pickup_location: "高新区环球中心租车点",
    features: "新能源 | 6座5门 | 自动挡 | 增程式",
    tags: "智能座舱,奶爸首选",
    image_url: "https://images.unsplash.com/photo-1617788138017-80ad40651399",
    is_featured: true,
    is_available: true,
    sales_rank: 507
  },

  # ============ 杭州 ============
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 125,
    total_price: 375,
    discount_amount: 40,
    location: "杭州",
    pickup_location: "萧山国际机场T3航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "机场特惠,经济热销",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 601
  },
  {
    brand: "本田",
    car_model: "思域",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 148,
    total_price: 444,
    discount_amount: 48,
    location: "杭州",
    pickup_location: "杭州东站东广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "高铁直达,运动时尚",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 602
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 178,
    total_price: 534,
    discount_amount: 58,
    location: "杭州",
    pickup_location: "杭州站南广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "火车站点,品质之选",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 603
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 308,
    total_price: 924,
    discount_amount: 80,
    location: "杭州",
    pickup_location: "武林广场租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务专车,市中心取车",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 604
  },
  {
    brand: "吉利",
    car_model: "几何A",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 168,
    total_price: 504,
    discount_amount: 60,
    location: "杭州",
    pickup_location: "西湖文化广场租车点",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "本土品牌,智能电动",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: true,
    is_available: true,
    sales_rank: 605
  },
  {
    brand: "特斯拉",
    car_model: "Model 3",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 285,
    total_price: 855,
    discount_amount: 95,
    location: "杭州",
    pickup_location: "钱江新城CBD租车点",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "智能驾驶,科技体验",
    image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89",
    is_featured: false,
    is_available: true,
    sales_rank: 606
  },

  # ============ 西安 ============
  {
    brand: "大众",
    car_model: "速腾",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.4T",
    price_per_day: 118,
    total_price: 354,
    discount_amount: 36,
    location: "西安",
    pickup_location: "咸阳国际机场T3航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.4T",
    tags: "机场直达,经济实惠",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 701
  },
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 105,
    total_price: 315,
    discount_amount: 30,
    location: "西安",
    pickup_location: "西安北站北广场租车中心",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "高铁站点,小车首选",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 702
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 165,
    total_price: 495,
    discount_amount: 50,
    location: "西安",
    pickup_location: "西安站南广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "火车站直达,舒适可靠",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 703
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 268,
    total_price: 804,
    discount_amount: 70,
    location: "西安",
    pickup_location: "钟楼商圈租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,市中心取车",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 704
  },
  {
    brand: "比亚迪",
    car_model: "秦PLUS DM-i",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "插电混动",
    engine: "混合动力",
    price_per_day: 138,
    total_price: 414,
    discount_amount: 45,
    location: "西安",
    pickup_location: "大雁塔北广场租车点",
    features: "新能源 | 5座4门 | 自动挡 | 插电混动",
    tags: "混动节能,低油耗",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: true,
    is_available: true,
    sales_rank: 705
  },

  # ============ 重庆 ============
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 120,
    total_price: 360,
    discount_amount: 38,
    location: "重庆",
    pickup_location: "江北国际机场T3航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "机场热销,经济之选",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 801
  },
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 108,
    total_price: 324,
    discount_amount: 32,
    location: "重庆",
    pickup_location: "重庆北站北广场租车中心",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "高铁站点,灵活小车",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 802
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 170,
    total_price: 510,
    discount_amount: 52,
    location: "重庆",
    pickup_location: "重庆西站西广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "高铁便捷,商务舒适",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 803
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 278,
    total_price: 834,
    discount_amount: 72,
    location: "重庆",
    pickup_location: "解放碑商圈租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务专车,CBD直达",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 804
  },
  {
    brand: "长安",
    car_model: "UNI-K",
    category: "SUV",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 238,
    total_price: 714,
    discount_amount: 65,
    location: "重庆",
    pickup_location: "观音桥商圈租车点",
    features: "SUV | 5座5门 | 自动挡 | 2.0T",
    tags: "本土品牌,智能SUV",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 805
  },

  # ============ 南京 ============
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 122,
    total_price: 366,
    discount_amount: 38,
    location: "南京",
    pickup_location: "禄口国际机场T2航站楼",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "机场专属,经济热销",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 901
  },
  {
    brand: "本田",
    car_model: "思域",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 145,
    total_price: 435,
    discount_amount: 45,
    location: "南京",
    pickup_location: "南京南站南广场租车中心",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "高铁站点,运动风格",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 902
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 175,
    total_price: 525,
    discount_amount: 55,
    location: "南京",
    pickup_location: "南京站北广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "火车站直达,可靠品质",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 903
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 298,
    total_price: 894,
    discount_amount: 78,
    location: "南京",
    pickup_location: "新街口商圈租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,市中心取车",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 904
  },

  # ============ 三亚 ============
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 135,
    total_price: 405,
    discount_amount: 40,
    location: "三亚",
    pickup_location: "凤凰国际机场航站楼",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "海岛自驾,小巧灵活",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 1001
  },
  {
    brand: "大众",
    car_model: "途观L",
    category: "SUV",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 288,
    total_price: 864,
    discount_amount: 80,
    location: "三亚",
    pickup_location: "三亚站东广场租车中心",
    features: "SUV | 5座5门 | 自动挡 | 2.0T",
    tags: "高铁便捷,海岛SUV",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 1002
  },
  {
    brand: "丰田",
    car_model: "普拉多",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "3.5L",
    price_per_day: 588,
    total_price: 1764,
    discount_amount: 150,
    location: "三亚",
    pickup_location: "大东海广场租车点",
    features: "SUV | 7座5门 | 自动挡 | 3.5L",
    tags: "豪华越野,海岛探险",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 1003
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 368,
    total_price: 1104,
    discount_amount: 100,
    location: "三亚",
    pickup_location: "三亚湾度假区租车服务站",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "家庭度假,多人出行",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 1004
  },
  {
    brand: "Jeep",
    car_model: "牧马人",
    category: "SUV",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 688,
    total_price: 2064,
    discount_amount: 200,
    location: "三亚",
    pickup_location: "海棠湾免税店租车点",
    features: "SUV | 5座4门 | 自动挡 | 2.0T",
    tags: "越野传奇,海岛自由",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: false,
    is_available: true,
    sales_rank: 1005
  }
]

# 批量插入汽车数据
timestamp = Time.current
cars_data_with_timestamps = cars_data.map { |data| data.merge(created_at: timestamp, updated_at: timestamp) }
Car.insert_all(cars_data_with_timestamps)

puts "Created #{Car.count} cars successfully!"
puts "Cities covered: 武汉, 深圳, 北京, 上海, 广州, 成都, 杭州, 西安, 重庆, 南京, 三亚"
