# 清空现有数据
Car.destroy_all

puts "Creating cars..."

cars_data = [
  {
    brand: "特斯拉",
    car_model: "Model 3",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 72,
    total_price: 324,
    discount_amount: 72,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "舒适轿车 | 5座4门 | 自动挡 | 纯电动",
    tags: "销量第一,机车特惠,VR看车",
    image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89",
    is_featured: true,
    is_available: true,
    sales_rank: 1
  },
  # 深圳机场租车点
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 120,
    total_price: 360,
    discount_amount: 40,
    location: "深圳",
    pickup_location: "宝安机场T3航站楼租车中心",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "城市热销,经济实惠",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 13
  },
  {
    brand: "别克",
    car_model: "凯越",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.3L",
    price_per_day: 95,
    total_price: 285,
    discount_amount: 50,
    location: "深圳",
    pickup_location: "宝安机场GTC地面交通中心",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.3L",
    tags: "总价最低,机车特惠",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: true,
    is_available: true,
    sales_rank: 14
  },
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 110,
    total_price: 330,
    discount_amount: 30,
    location: "深圳",
    pickup_location: "宝安机场停车场租车点",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "低价好车,城市热销",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 15
  },
  # 深圳火车站租车点
  {
    brand: "丰田",
    car_model: "卡罗拉",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 105,
    total_price: 315,
    discount_amount: 35,
    location: "深圳",
    pickup_location: "深圳北站西广场租车中心",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "车站便捷,热门车型",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: true,
    is_available: true,
    sales_rank: 101
  },
  {
    brand: "日产",
    car_model: "轩逸",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.6L",
    price_per_day: 130,
    total_price: 390,
    discount_amount: 45,
    location: "深圳",
    pickup_location: "深圳北站东广场停车场",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.6L",
    tags: "舒适经济,车站专属",
    image_url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6",
    is_featured: false,
    is_available: true,
    sales_rank: 102
  },
  {
    brand: "比亚迪",
    car_model: "秦PLUS DM-i",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "插电混动",
    engine: "混合动力",
    price_per_day: 115,
    total_price: 345,
    discount_amount: 50,
    location: "深圳",
    pickup_location: "深圳站罗湖口岸租车点",
    features: "新能源 | 5座4门 | 自动挡 | 插电混动",
    tags: "新能源,节能环保",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: false,
    is_available: true,
    sales_rank: 103
  },
  {
    brand: "吉利",
    car_model: "帝豪GL",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.4T",
    price_per_day: 98,
    total_price: 294,
    discount_amount: 40,
    location: "深圳",
    pickup_location: "深圳西站租车服务点",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.4T",
    tags: "实惠之选,口碑好车",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: false,
    is_available: true,
    sales_rank: 104
  },
  # 深圳福田区租车点
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 180,
    total_price: 540,
    discount_amount: 60,
    location: "深圳",
    pickup_location: "福田中心区会展中心租车点",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "商务首选,CBD专属",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: true,
    is_available: true,
    sales_rank: 105
  },
  {
    brand: "大众",
    car_model: "帕萨特",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.8T",
    price_per_day: 175,
    total_price: 525,
    discount_amount: 55,
    location: "深圳",
    pickup_location: "福田区市民中心租车服务站",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.8T",
    tags: "政务商务,品质保证",
    image_url: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982",
    is_featured: false,
    is_available: true,
    sales_rank: 106
  },
  {
    brand: "特斯拉",
    car_model: "Model 3",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 280,
    total_price: 840,
    discount_amount: 100,
    location: "深圳",
    pickup_location: "福田区皇岗口岸租车中心",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "智能电动,科技体验",
    image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89",
    is_featured: true,
    is_available: true,
    sales_rank: 107
  },
  # 深圳南山区租车点
  {
    brand: "奔驰",
    car_model: "C级",
    category: "豪华轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 350,
    total_price: 1050,
    discount_amount: 120,
    location: "深圳",
    pickup_location: "南山区科技园租车中心",
    features: "豪华轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "豪华商务,科技园专属",
    image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8",
    is_featured: true,
    is_available: true,
    sales_rank: 108
  },
  {
    brand: "宝马",
    car_model: "3系",
    category: "豪华轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 380,
    total_price: 1140,
    discount_amount: 130,
    location: "深圳",
    pickup_location: "南山区蛇口海上世界租车点",
    features: "豪华轿车 | 5座4门 | 自动挡 | 2.0T",
    tags: "豪华驾控,海滨专属",
    image_url: "https://images.unsplash.com/photo-1555215695-3004980ad54e",
    is_featured: false,
    is_available: true,
    sales_rank: 109
  },
  {
    brand: "丰田",
    car_model: "汉兰达",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 260,
    total_price: 780,
    discount_amount: 80,
    location: "深圳",
    pickup_location: "南山区欢乐海岸租车服务站",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "家庭首选,空间宽敞",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 110
  },
  # 深圳罗湖区租车点
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 320,
    total_price: 960,
    discount_amount: 100,
    location: "深圳",
    pickup_location: "罗湖区东门商业街租车点",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,舒适空间",
    image_url: "https://images.unsplash.com/photo-1464219789935-c2d9d9aba644",
    is_featured: false,
    is_available: true,
    sales_rank: 111
  },
  {
    brand: "丰田",
    car_model: "凯美瑞",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 165,
    total_price: 495,
    discount_amount: 55,
    location: "深圳",
    pickup_location: "罗湖区万象城租车服务点",
    features: "舒适轿车 | 5座4门 | 自动挡 | 2.0L",
    tags: "品质之选,商圈便捷",
    image_url: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb",
    is_featured: false,
    is_available: true,
    sales_rank: 112
  },
  # 深圳龙岗区租车点
  {
    brand: "本田",
    car_model: "CR-V",
    category: "SUV",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 220,
    total_price: 660,
    discount_amount: 70,
    location: "深圳",
    pickup_location: "龙岗中心城租车服务站",
    features: "SUV | 5座5门 | 自动挡 | 1.5T",
    tags: "家用SUV,实用舒适",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: false,
    is_available: true,
    sales_rank: 113
  },
  {
    brand: "大众",
    car_model: "途观L",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 240,
    total_price: 720,
    discount_amount: 75,
    location: "深圳",
    pickup_location: "龙岗区坂田租车中心",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "大空间,家庭出游",
    image_url: "https://images.unsplash.com/photo-1464219789935-c2d9d9aba644",
    is_featured: false,
    is_available: true,
    sales_rank: 114
  },
  # 深圳宝安区租车点
  {
    brand: "比亚迪",
    car_model: "唐DM",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "插电混动",
    engine: "混合动力",
    price_per_day: 250,
    total_price: 750,
    discount_amount: 85,
    location: "深圳",
    pickup_location: "宝安区西乡租车服务站",
    features: "SUV | 7座5门 | 自动挡 | 插电混动",
    tags: "新能源SUV,动力强劲",
    image_url: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982",
    is_featured: false,
    is_available: true,
    sales_rank: 115
  },
  {
    brand: "理想",
    car_model: "L8",
    category: "SUV",
    seats: 6,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "增程式",
    engine: "混合动力",
    price_per_day: 450,
    total_price: 1350,
    discount_amount: 150,
    location: "深圳",
    pickup_location: "宝安区沙井租车中心",
    features: "SUV | 6座5门 | 自动挡 | 增程式",
    tags: "智能豪华,家庭首选",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 116
  },
  # 深圳龙华区租车点
  {
    brand: "蔚来",
    car_model: "ES6",
    category: "新能源",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 380,
    total_price: 1140,
    discount_amount: 130,
    location: "深圳",
    pickup_location: "龙华区民治租车服务点",
    features: "新能源 | 5座5门 | 自动挡 | 纯电动",
    tags: "智能电动,科技豪华",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: true,
    is_available: true,
    sales_rank: 117
  },
  {
    brand: "小鹏",
    car_model: "P7",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 300,
    total_price: 900,
    discount_amount: 110,
    location: "深圳",
    pickup_location: "龙华区观澜租车中心",
    features: "新能源 | 5座4门 | 自动挡 | 纯电动",
    tags: "智能驾驶,电动轿跑",
    image_url: "https://images.unsplash.com/photo-1560958089-b8a1929cea89",
    is_featured: false,
    is_available: true,
    sales_rank: 118
  },
  # 深圳盐田区租车点
  {
    brand: "Jeep",
    car_model: "牧马人",
    category: "SUV",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 500,
    total_price: 1500,
    discount_amount: 150,
    location: "深圳",
    pickup_location: "盐田区大梅沙租车服务站",
    features: "SUV | 5座5门 | 自动挡 | 2.0T",
    tags: "越野硬汉,海滨自驾",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: false,
    is_available: true,
    sales_rank: 119
  },
  {
    brand: "丰田",
    car_model: "普拉多",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "3.5L",
    price_per_day: 550,
    total_price: 1650,
    discount_amount: 170,
    location: "深圳",
    pickup_location: "盐田港租车中心",
    features: "SUV | 7座5门 | 自动挡 | 3.5L",
    tags: "硬派越野,探险首选",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: false,
    is_available: true,
    sales_rank: 120
  },
  # 成都7座SUV
  {
    brand: "丰田",
    car_model: "汉兰达",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 280,
    total_price: 840,
    discount_amount: 80,
    location: "成都",
    pickup_location: "双流机场租车点",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "家庭首选,宽敞舒适",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: true,
    is_available: true,
    sales_rank: 16
  },
  {
    brand: "别克",
    car_model: "昂科雷",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 260,
    total_price: 780,
    discount_amount: 70,
    location: "成都",
    pickup_location: "市区租车中心",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "家庭出行,大空间",
    image_url: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982",
    is_featured: true,
    is_available: true,
    sales_rank: 17
  },
  {
    brand: "大众",
    car_model: "途观L",
    category: "SUV",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 300,
    total_price: 900,
    discount_amount: 90,
    location: "成都",
    pickup_location: "成华大道租车点",
    features: "SUV | 7座5门 | 自动挡 | 2.0T",
    tags: "家庭豪华游,适合长途",
    image_url: "https://images.unsplash.com/photo-1464219789935-c2d9d9aba644",
    is_featured: true,
    is_available: true,
    sales_rank: 18
  },
  {
    brand: "别克",
    car_model: "凯越",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.3L",
    price_per_day: 11,
    total_price: 42,
    discount_amount: 50,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.3L",
    tags: "总价最低,机车特惠",
    image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf",
    is_featured: true,
    is_available: true,
    sales_rank: 2
  },
  {
    brand: "丰田",
    car_model: "锋兰达",
    category: "SUV",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 29,
    total_price: 78,
    discount_amount: 50,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "SUV | 5座5门 | 自动挡 | 2.0L",
    tags: "机车特惠,VR看车",
    image_url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b",
    is_featured: false,
    is_available: true,
    sales_rank: 3
  },
  {
    brand: "本田",
    car_model: "飞度",
    category: "经济轿车",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 26,
    total_price: 104,
    discount_amount: 30,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "经济轿车 | 5座5门 | 自动挡 | 1.5L",
    tags: "低价好车,城市热销",
    image_url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d",
    is_featured: true,
    is_available: true,
    sales_rank: 4
  },
  {
    brand: "大众",
    car_model: "朗逸",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 36,
    total_price: 144,
    discount_amount: 40,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "城市热销",
    image_url: "https://images.unsplash.com/photo-1580273916550-e323be2ae537",
    is_featured: true,
    is_available: true,
    sales_rank: 5
  },
  {
    brand: "丰田",
    car_model: "RAV4荣放",
    category: "SUV",
    seats: 5,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0L",
    price_per_day: 34,
    total_price: 136,
    discount_amount: 35,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "SUV | 5座5门 | 自动挡 | 2.0L",
    tags: "",
    image_url: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982",
    is_featured: false,
    is_available: true,
    sales_rank: 6
  },
  {
    brand: "雪佛兰",
    car_model: "科鲁兹",
    category: "经济轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5L",
    price_per_day: 34,
    total_price: 136,
    discount_amount: 35,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "经济轿车 | 5座4门 | 自动挡 | 1.5L",
    tags: "",
    image_url: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2",
    is_featured: false,
    is_available: true,
    sales_rank: 7
  },
  {
    brand: "比亚迪",
    car_model: "秦PLUS DM-i",
    category: "新能源",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "插电混动",
    engine: "混合动力",
    price_per_day: 35,
    total_price: 140,
    discount_amount: 40,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "新能源 | 5座4门 | 自动挡 | 插电混动",
    tags: "新能源车,环保节能",
    image_url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7",
    is_featured: false,
    is_available: true,
    sales_rank: 8
  },
  {
    brand: "五菱",
    car_model: "宏光MINIEV",
    category: "新能源",
    seats: 4,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "纯电动",
    engine: "电动",
    price_per_day: 18,
    total_price: 72,
    discount_amount: 25,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "新能源 | 4座4门 | 自动挡 | 纯电动",
    tags: "新能源车,小巧灵活",
    image_url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24",
    is_featured: false,
    is_available: true,
    sales_rank: 9
  },
  {
    brand: "本田",
    car_model: "雅阁",
    category: "舒适轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "1.5T",
    price_per_day: 58,
    total_price: 232,
    discount_amount: 60,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "舒适轿车 | 5座4门 | 自动挡 | 1.5T",
    tags: "商务首选",
    image_url: "https://images.unsplash.com/photo-1590362891991-f776e747a588",
    is_featured: false,
    is_available: true,
    sales_rank: 10
  },
  {
    brand: "别克",
    car_model: "GL8",
    category: "商务车",
    seats: 7,
    doors: 5,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 150,
    total_price: 600,
    discount_amount: 80,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "商务车 | 7座5门 | 自动挡 | 2.0T",
    tags: "商务接待,宽敞舒适",
    image_url: "https://images.unsplash.com/photo-1464219789935-c2d9d9aba644",
    is_featured: false,
    is_available: true,
    sales_rank: 11
  },
  {
    brand: "奔驰",
    car_model: "E级",
    category: "豪华轿车",
    seats: 5,
    doors: 4,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 380,
    total_price: 1520,
    discount_amount: 100,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "豪华轿车 | 5座4门 | 自动挡 | 2.0T",
    tags: "豪华商务,尊贵体验",
    image_url: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8",
    is_featured: false,
    is_available: true,
    sales_rank: 12
  },
  {
    brand: "保时捷",
    car_model: "718",
    category: "跑车",
    seats: 2,
    doors: 2,
    transmission: "自动挡",
    fuel_type: "汽油",
    engine: "2.0T",
    price_per_day: 900,
    total_price: 3600,
    discount_amount: 200,
    location: "武汉",
    pickup_location: "天河国际机场T3",
    features: "跑车 | 2座2门 | 自动挡 | 2.0T",
    tags: "超跑体验,激情驾驶",
    image_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70",
    is_featured: false,
    is_available: true,
    sales_rank: 13
  }
]

# 批量插入汽车数据
timestamp = Time.current
cars_data_with_timestamps = cars_data.map { |data| data.merge(created_at: timestamp, updated_at: timestamp) }
Car.insert_all(cars_data_with_timestamps)

puts "Created #{Car.count} cars successfully!"
