# frozen_string_literal: true

# 包车游数据包 v1
# 包含武汉地区的包车游路线、景点和车型数据
#
# 用途：
# - 初始化包车游系统的基础数据
# - 提供测试和演示数据
#
# 加载方式：
# rails runner "load Rails.root.join('app/validators/support/data_packs/v1/chartered_tours.rb')"

puts "正在加载包车游数据包 v1..."

# 确保武汉城市存在
wuhan = City.find_or_create_by!(name: '武汉') do |city|
  city.pinyin = 'wuhan'
  city.region = '华中'
  city.is_hot = true
end

puts "  ✓ 城市: #{wuhan.name}"

# 1. 创建景点
attractions_data = [
  {
    name: '黄鹤楼',
    city_id: wuhan.id,
    latitude: 30.5450,
    longitude: 114.2968,
    description: '江南三大名楼之一，"昔人已乘黄鹤去，此地空余黄鹤楼"',
    cover_image_url: 'https://images.unsplash.com/photo-1580836572436-7f8e60ec0d99'
  },
  {
    name: '武汉大学',
    city_id: wuhan.id,
    latitude: 30.5327,
    longitude: 114.3671,
    description: '中国最美大学之一，樱花季美景如画',
    cover_image_url: 'https://images.unsplash.com/photo-1562774053-701939374585'
  },
  {
    name: '湖北省博物馆',
    city_id: wuhan.id,
    latitude: 30.5613,
    longitude: 114.3708,
    description: '编钟之乡，珍藏曾侯乙编钟等国宝',
    cover_image_url: 'https://images.unsplash.com/photo-1566127992631-137a642a90f4'
  },
  {
    name: '东湖听涛景区',
    city_id: wuhan.id,
    latitude: 30.5672,
    longitude: 114.3918,
    description: '中国最大的城中湖，风景秀丽',
    cover_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4'
  },
  {
    name: '长江荣耀号游船',
    city_id: wuhan.id,
    latitude: 30.5833,
    longitude: 114.3054,
    description: '乘船游览长江，感受武汉两江交汇的壮观',
    cover_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5'
  },
  {
    name: '古德寺',
    city_id: wuhan.id,
    latitude: 30.6103,
    longitude: 114.2858,
    description: '建筑风格独特的佛教寺院',
    cover_image_url: 'https://images.unsplash.com/photo-1548013146-72479768bada'
  },
  {
    name: '晴川阁',
    city_id: wuhan.id,
    latitude: 30.5499,
    longitude: 114.2752,
    description: '楚天第一名楼，与黄鹤楼隔江相望',
    cover_image_url: 'https://images.unsplash.com/photo-1601301350837-4e6070a0795c'
  },
  {
    name: '三峡大坝',
    city_id: wuhan.id,
    latitude: 30.8235,
    longitude: 111.0025,
    description: '世界最大水利枢纽工程（武汉周边）',
    cover_image_url: 'https://images.unsplash.com/photo-1572481449884-bdb0e25be4da'
  },
  {
    name: '神农架',
    city_id: wuhan.id,
    latitude: 31.7448,
    longitude: 110.6717,
    description: '原始森林，神秘野人传说（武汉周边）',
    cover_image_url: 'https://images.unsplash.com/photo-1511497584788-876760111969'
  }
]

Attraction.insert_all(attractions_data)
attractions = Attraction.by_city(wuhan.id).index_by(&:name)

puts "  ✓ 景点: #{attractions.size}个"

# 2. 创建车型
vehicle_types_data = [
  {
    name: '经济5座',
    category: '5座',
    level: '经济',
    seats: 5,
    luggage_capacity: 2,
    hourly_price_6h: 308.0,
    hourly_price_8h: 388.0,
    included_mileage: 100,
    image_url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2'
  },
  {
    name: '舒适5座',
    category: '5座',
    level: '舒适',
    seats: 5,
    luggage_capacity: 2,
    hourly_price_6h: 378.0,
    hourly_price_8h: 478.0,
    included_mileage: 100,
    image_url: 'https://images.unsplash.com/photo-1563720360172-67b8f3dce741'
  },
  {
    name: '经济7座',
    category: '7座',
    level: '经济',
    seats: 7,
    luggage_capacity: 3,
    hourly_price_6h: 428.0,
    hourly_price_8h: 528.0,
    included_mileage: 100,
    image_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b'
  },
  {
    name: '舒适7座',
    category: '7座',
    level: '舒适',
    seats: 7,
    luggage_capacity: 3,
    hourly_price_6h: 528.0,
    hourly_price_8h: 628.0,
    included_mileage: 100,
    image_url: 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d'
  },
  {
    name: '商务巴士',
    category: '巴士',
    level: '舒适',
    seats: 15,
    luggage_capacity: 10,
    hourly_price_6h: 888.0,
    hourly_price_8h: 1088.0,
    included_mileage: 100,
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957'
  }
]

VehicleType.insert_all(vehicle_types_data)
vehicle_types = VehicleType.all.index_by(&:name)

puts "  ✓ 车型: #{vehicle_types.size}种"

# 3. 创建包车路线
routes_data = [
  {
    name: '1日游 | 黄鹤楼+武汉大学+湖北省博物馆+东湖听涛景区+长江荣耀号游船',
    city_id: wuhan.id,
    slug: nil, # Will be generated by FriendlyId
    duration_days: 1,
    distance_km: 50,
    category: 'hot',
    description: '武汉经典一日游，游览著名景点，含游船体验',
    price_from: 450.0,
    highlights: ['黄鹤楼登高望远', '武大赏樱花', '编钟演奏', '东湖泛舟', '长江游船'].to_json,
    cover_image_url: 'https://images.unsplash.com/photo-1580836572436-7f8e60ec0d99'
  },
  {
    name: '1日游 | 黄鹤楼+武汉大学+湖北省博物馆+东湖听涛景区',
    city_id: wuhan.id,
    slug: nil,
    duration_days: 1,
    distance_km: 40,
    category: 'featured',
    description: '精华四大景点游览，轻松舒适',
    price_from: 400.0,
    highlights: ['黄鹤楼', '武大', '省博物馆', '东湖'].to_json,
    cover_image_url: 'https://images.unsplash.com/photo-1562774053-701939374585'
  },
  {
    name: '1日游 | 黄鹤楼+古德寺+晴川阁+湖北省博物馆+东湖生态旅游风景区',
    city_id: wuhan.id,
    slug: nil,
    duration_days: 1,
    distance_km: 55,
    category: 'classic',
    description: '文化深度游，感受武汉历史底蕴',
    price_from: 480.0,
    highlights: ['黄鹤楼', '古德寺', '晴川阁', '省博物馆', '东湖'].to_json,
    cover_image_url: 'https://images.unsplash.com/photo-1566127992631-137a642a90f4'
  },
  {
    name: '1日游 | 武汉市区包车游',
    city_id: wuhan.id,
    slug: nil,
    duration_days: 1,
    distance_km: 60,
    category: 'featured',
    description: '市区精华景点自由组合，灵活安排',
    price_from: 350.0,
    highlights: ['行程自由', '景点可选', '司机推荐'].to_json,
    cover_image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4'
  },
  {
    name: '1日游 | 恩施包车游',
    city_id: wuhan.id,
    slug: nil,
    duration_days: 1,
    distance_km: 120,
    category: 'hot',
    description: '恩施大峡谷/恩施土司城一日往返',
    price_from: 650.0,
    highlights: ['恩施大峡谷', '土司城'].to_json,
    cover_image_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b'
  },
  {
    name: '2日游 | 宜昌三峡大坝+神农架',
    city_id: wuhan.id,
    slug: nil,
    duration_days: 2,
    distance_km: 500,
    category: 'classic',
    description: '游览世界最大水利工程和原始森林',
    price_from: 1200.0,
    highlights: ['三峡大坝', '神农架原始森林', '野人传说'].to_json,
    cover_image_url: 'https://images.unsplash.com/photo-1572481449884-bdb0e25be4da'
  }
]

CharterRoute.insert_all(routes_data)
routes = CharterRoute.by_city(wuhan.id).index_by(&:name)

puts "  ✓ 路线: #{routes.size}条"

# 4. 创建路线-景点关联
route_attractions_data = []

# 路线1: 5个景点
route1 = routes['1日游 | 黄鹤楼+武汉大学+湖北省博物馆+东湖听涛景区+长江荣耀号游船']
[attractions['黄鹤楼'], attractions['武汉大学'], attractions['湖北省博物馆'], 
 attractions['东湖听涛景区'], attractions['长江荣耀号游船']].each_with_index do |attraction, index|
  route_attractions_data << {
    charter_route_id: route1.id,
    attraction_id: attraction.id,
    position: index
  }
end

# 路线2: 4个景点
route2 = routes['1日游 | 黄鹤楼+武汉大学+湖北省博物馆+东湖听涛景区']
[attractions['黄鹤楼'], attractions['武汉大学'], attractions['湖北省博物馆'], 
 attractions['东湖听涛景区']].each_with_index do |attraction, index|
  route_attractions_data << {
    charter_route_id: route2.id,
    attraction_id: attraction.id,
    position: index
  }
end

# 路线3: 5个景点
route3 = routes['1日游 | 黄鹤楼+古德寺+晴川阁+湖北省博物馆+东湖生态旅游风景区']
[attractions['黄鹤楼'], attractions['古德寺'], attractions['晴川阁'], 
 attractions['湖北省博物馆'], attractions['东湖听涛景区']].each_with_index do |attraction, index|
  route_attractions_data << {
    charter_route_id: route3.id,
    attraction_id: attraction.id,
    position: index
  }
end

# 路线4: 3个景点
route4 = routes['1日游 | 武汉市区包车游']
[attractions['黄鹤楼'], attractions['武汉大学'], attractions['东湖听涛景区']].each_with_index do |attraction, index|
  route_attractions_data << {
    charter_route_id: route4.id,
    attraction_id: attraction.id,
    position: index
  }
end

# 路线6: 2个景点
route6 = routes['2日游 | 宜昌三峡大坝+神农架']
[attractions['三峡大坝'], attractions['神农架']].each_with_index do |attraction, index|
  route_attractions_data << {
    charter_route_id: route6.id,
    attraction_id: attraction.id,
    position: index
  }
end

RouteAttraction.insert_all(route_attractions_data)

puts "  ✓ 路线景点关联: #{route_attractions_data.size}个"

puts "\n✓ 包车游数据包加载完成！"
puts "  - 城市: 1个 (武汉)"
puts "  - 景点: #{attractions.size}个"
puts "  - 车型: #{vehicle_types.size}种"
puts "  - 路线: #{routes.size}条"
puts "  - 关联: #{route_attractions_data.size}个"
