class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for trains generated by controller generator
  resources :trains, only: [:index] do
    collection do
      get :search
    end
  end
  # End routes for trains

  # Routes for destinations generated by controller generator
  resources :destinations, only: [:index, :show] do
    collection do
      get :select
    end
  end
  # End routes for destinations

  # Routes for bookings
  resources :bookings, only: [:index, :new, :create, :show] do
    member do
      patch :cancel
      patch :pay
      get :success
    end
  end
  # End routes for bookings

  # Authentication routes generated by authentication generator
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resource :session, only: [:new, :show, :destroy] do
    get :devices, on: :member
    delete :destroy_one, on: :member
  end
  resources :registrations, only: [:new, :create]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  resource :invitation, only: [:new, :create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles' do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # Authentication routes generated end

  # Routes for flights generated by controller generator
  resources :flights, only: [:index, :show] do
    collection do
      get :search
    end
  end
  # End routes for flights

  # write your business logic routes here

  # API routes
  namespace :api do
    # 验证任务 API
    resources :validation_tasks, only: [ :create, :show, :destroy ] do
      member do
        post :verify
      end
    end
    
    # Check membership status (no version namespace needed for internal API)
    get 'check_membership', to: 'memberships#check'
    
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :flight_offers
    resources :passengers
    resources :bookings
    resources :flights
    resources :users
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
