class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for abroad_ticket_orders generated by controller generator
  resources :abroad_ticket_orders, only: [:new, :create, :show, :destroy] do
    member do
      patch :pay
      get :success
    end
  end
  # End routes for abroad_ticket_orders

  # Routes for abroad_tickets generated by controller generator
  resources :abroad_tickets, only: [:index, :show] do
    collection do
      get :search
    end
  end
  # End routes for abroad_tickets

  # Routes for addresses generated by controller generator
  resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy]
  # End routes for addresses

  # Routes for internet_orders generated by controller generator
  resources :internet_orders, only: [:index, :new, :create, :destroy] do
    member do
      get :success
    end
  end
  # End routes for internet_orders

  # Routes for internet_services generated by controller generator
  resources :internet_services, only: [:index] do
    get :sim_cards
    get :data_plans
    get :wifis
  end
  # End routes for internet_services

  # Routes for abroad_coupons generated by controller generator
  resources :abroad_coupons, only: [:show] do
    collection do
      get :wallet
    end
    member do
      post :claim
    end
  end
  # End routes for abroad_coupons

  # Routes for abroad_shops generated by controller generator
  resources :abroad_shops, only: [:index] do
    collection do
      get :search
      get :cosmeceuticals
      get :duty_free
    end
    member do
      get :brand
      get :shop
    end
  end
  # End routes for abroad_shops

  # Routes for deep_travel_bookings generated by controller generator
  resources :deep_travel_bookings, only: [:new, :create, :show, :destroy] do
    member do
      patch :pay
      get :success
    end
  end
  # End routes for deep_travel_bookings

  # Routes for bus_ticket_orders generated by controller generator
  resources :bus_ticket_orders, only: [:new, :create, :destroy] do
    member do
      patch :pay
      get :success
    end
  end
  # End routes for bus_ticket_orders

  # Routes for bus_tickets generated by controller generator
  resources :bus_tickets, only: [:index, :show] do
    collection do
      get :search
      get :count_filtered_results
    end
  end
  # End routes for bus_tickets

  # PWA routes
  get '/manifest.json', to: 'pwa#manifest', defaults: { format: :json }
  get '/service-worker.js', to: 'pwa#service_worker', defaults: { format: :js }
  # Routes for hotel_package_orders generated by controller generator
  resources :hotel_package_orders, only: [:new, :create, :show] do
    member do
      get :success
    end
  end
  # End routes for hotel_package_orders

  # Routes for car_orders generated by controller generator
  resources :car_orders, only: [:new, :create, :destroy]
  # End routes for car_orders

  # Routes for cars generated by controller generator
  resources :cars, only: [:index, :show] do
    collection do
      get :search
    end
  end
  # End routes for cars

  # Routes for car_orders
  resources :car_orders, only: [:new, :create, :show] do
    member do
      patch :pay
      get :success
    end
  end
  # End routes for car_orders

  # Routes for train_bookings generated by controller generator
  resources :train_bookings, only: [:new, :create, :show] do
    member do
      get :success
      get :lock
      patch :pay
      patch :cancel
    end
  end
  # End routes for train_bookings

  # Routes for tour_group_bookings generated by controller generator
  resources :tour_group_bookings, only: [:new, :create, :show] do
    member do
      get :success
      patch :pay
    end
  end
  # End routes for tour_group_bookings

  # Routes for tour_groups generated by controller generator
  resources :tour_groups, only: [:index, :show] do
    collection do
      get :search
    end
  end
  # End routes for tour_groups

  # Routes for hotel_packages generated by controller generator
  resources :hotel_packages, only: [:index, :show] do
    collection do
      get :search
    end
  end
  # End routes for hotel_packages

  # API routes
  namespace :api do
    post 'geocoding/reverse', to: 'geocodings#reverse_geocode'
  end

  # Routes for hotel_bookings generated by controller generator
  resources :hotel_bookings, only: [:create, :show] do
    member do
      get :success
      patch :pay
    end
  end
  
  # Routes for hotels with nested bookings
  resources :hotels, only: [:index, :show] do
    resources :hotel_bookings, only: [:new]
    collection do
      get :search
    end
    member do
      get :policy
    end
  end
  # End routes for hotels and hotel_bookings

  # Routes for homestays
  resources :homestays, only: [:index] do
    collection do
      get :search
    end
  end
  # End routes for homestays

  # Routes for deep_travels generated by controller generator
  resources :deep_travels, only: [:index, :show]
  # End routes for deep_travels

  # Routes for trips generated by controller generator
  resources :trips, only: [:index] do
    collection do
      get :load_more
    end
  end
  # End routes for trips

  # Routes for messages generated by controller generator
  resources :messages, only: [:index]
  # End routes for messages
  
  # Routes for notifications
  resources :notifications, only: [:show] do
    collection do
      get ':category', to: 'notifications#category', as: :category, constraints: { category: /[a-z_]+/ }
    end
    member do
      patch :mark_as_read
    end
  end

  # Routes for members generated by controller generator
  resources :members, only: [:index]
  # End routes for members

  # Routes for trains generated by controller generator
  resources :trains, only: [:index, :show] do
    collection do
      get :search
    end
  end
  # End routes for trains

  # Routes for tourism
  resources :tourism, only: [:index], path: 'tourism' do
    collection do
      get :search
    end
  end
  # End routes for tourism

  # Routes for destinations generated by controller generator
  resources :destinations, only: [:index, :show] do
    collection do
      get :select
    end
  end
  # End routes for destinations

  # Routes for bookings
  resources :bookings, only: [:index, :new, :create, :show] do
    member do
      patch :cancel
      patch :pay
      get :success
    end
  end
  # End routes for bookings

  # Authentication routes generated by authentication generator
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resource :session, only: [:new, :show, :destroy] do
    get :devices, on: :member
    delete :destroy_one, on: :member
  end
  resources :registrations, only: [:new, :create]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  resource :invitation, only: [:new, :create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles' do
    member do
      get :edit_password
      patch :update_password
      get :edit_pay_password
      patch :update_pay_password
      post :verify_pay_password
    end
  end

  # Authentication routes generated end

  # Routes for flights generated by controller generator
  resources :flights, only: [:index, :show] do
    collection do
      get :search
      get :combinations
      get :multi_city_search, to: 'flights#multi_city_search'
      get :multi_city_results, to: 'flights#multi_city_results'
    end
  end
  # End routes for flights

  # Special flights (only index page, search redirects to flights/search?sort_by=price)
  resources :special_flights, only: [:index]

  # Routes for passengers (常用信息)
  resources :passengers, only: [:index, :new, :create, :edit, :update, :destroy]

  # write your business logic routes here

  # API routes
  namespace :api do
    # 验证任务 API
    resources :validation_tasks, only: [ :create, :show, :destroy ] do
      member do
        post :verify
      end
    end
    
    # Check membership status (no version namespace needed for internal API)
    get 'check_membership', to: 'memberships#check'
    
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :bus_tickets
    resources :cars do
      collection do
        get :generator
        post :batch_generate
      end
    end
    resources :hotel_packages do
      collection do
        get :generator
        post :batch_generate
      end
    end
    resources :tour_group_products do
      collection do
        get :generator
        post :batch_generate
      end
    end
    resources :travel_agencies
    resources :hotels do
      collection do
        post :generate_batch
      end
    end
    resources :deep_travel_products
    resources :deep_travel_guides
    resources :flight_offers
    resources :passengers
    resources :bookings
    resources :flights do
      collection do
        get :generator
        post :batch_generate
      end
    end
    resources :trains do
      collection do
        get :generator
        post :batch_generate
      end
    end
    resources :users
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
